package mealplanner;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;

public class DatabaseManager {
    private String URL_DB = "jdbc:postgresql:meals_db"; //jdbc - это протокол; postgresql - тип базы; meals_db - имя базы
    private String USER = "postgres";
    private String PASS = "1111";
    private Connection connection;

    public void connect() {
        try {
            connection = DriverManager.getConnection(URL_DB, USER, PASS);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

    }

    public Connection getConnection() {
        return connection;
    }

    public void closeConnetion(){
        if(connection != null){
            try {
                connection.close();
            }catch (SQLException e){
                throw new RuntimeException(e);
            }
        }
    }

    public void init() {
        try(Statement statement = connection.createStatement()) { //создает объект Statement
            String createMealTableSQL = "CREATE TABLE IF NOT EXISTS meals (" +
                    "meal_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "category VARCHAR NOT NULL," +
                    "meal VARCHAR NOT NULL" +
                    ")";
            statement.executeUpdate(createMealTableSQL); //выполнить SQL-запрос

            String createIngredientsTableSQL = "CREATE TABLE IF NOT EXISTS ingredients (" +
                    "ingredient_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "ingredient VARCHAR NOT NULL," +
                    "meal_id INTEGER REFERENCES meals(meal_id)" +
                    ")";

            statement.executeUpdate(createIngredientsTableSQL);

            String createPlanTableSQL = "CREATE TABLE IF NOT EXISTS plan (" +
                    "plan_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "meal_category VARCHAR NOT NULL," +
                    "day_of_week VARCHAR NOT NULL," +
                    "meal_id INTEGER REFERENCES meals(meal_id)," +
                    "CONSTRAINT unique_day_category UNIQUE (day_of_week, meal_category)" +
                    //CONSTRAINT unique_day_category - имя для ограничения UNIQUE
                    ")";
            statement.executeUpdate(createPlanTableSQL);

        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }
}
